import type { ChatResource } from '@/api/chats';
import type { ContactResource } from '@/api/contacts';
import type { LabelResource } from '@/api/labels';
import { Button, Inspector, StateNotice, Status, Surface } from '@/components/v2';
import { humanizeToken, relativeTime } from '@/lib/format';
import { useMessageV2, useReceiptsV2 } from './hooks';
import { FailureNoticeV2, ProjectionStatusV2 } from './ui';

export function DirectoryInspectorV2({ contact, label, error, loading, onRetry, onClose }: { contact?: ContactResource; label?: LabelResource; error?: unknown; loading: boolean; onRetry: () => void; onClose: () => void }) {
  const title = contact?.displayName ?? label?.name ?? (contact ? contact.id : label?.id) ?? 'Directory details';
  return <Inspector titleId="directory-v2-details" eyebrow={contact ? 'Projected contact' : 'Projected label'} title={title} modal onClose={onClose}>
    {loading ? <StateNotice value={{ axis: 'resource', state: 'initial-loading' }} /> : error && !contact && !label ? <FailureNoticeV2 error={error} onRetry={onRetry} /> : contact ? <Surface title="Normalized identity" description="Read-only projection; phone identity is redacted by the backend."><dl className="ui-v2-detail-list"><div><dt>JID</dt><dd className="ui-v2-mono">{contact.id}</dd></div><div><dt>Username</dt><dd>{contact.username ?? 'Not reported'}</dd></div><div><dt>Phone</dt><dd>{contact.redactedPhone ?? 'Not reported'}</dd></div><div><dt>Business</dt><dd>{contact.businessName ?? 'Not reported'}</dd></div><div><dt>About</dt><dd>{contact.about ?? 'Not reported'}</dd></div><div><dt>Known</dt><dd>{contact.found ? 'Yes' : 'No'}</dd></div></dl>{error ? <FailureNoticeV2 error={error} stale onRetry={onRetry} /> : null}</Surface> : label ? <Surface title="Projected definition" description="Definitions are read-only; Console does not infer chat-label assignments."><dl className="ui-v2-detail-list"><div><dt>Label ID</dt><dd className="ui-v2-mono">{label.id}</dd></div><div><dt>Name</dt><dd>{label.name ?? 'Not reported'}</dd></div><div><dt>Color</dt><dd>{label.color ?? 'Not reported'}</dd></div><div><dt>Predefined ID</dt><dd>{label.predefinedId ?? 'Not reported'}</dd></div></dl>{error ? <FailureNoticeV2 error={error} stale onRetry={onRetry} /> : null}</Surface> : <StateNotice value={{ axis: 'resource', state: 'empty' }} detail="The selected projected definition was not returned." />}
  </Inspector>;
}

export function MessageInspectorV2({ messageId, loadedChat, enabled, onClose }: { messageId: string; loadedChat?: ChatResource; enabled: boolean; onClose: () => void }) {
  const message = useMessageV2(messageId, enabled);
  const resource = message.data?.resource;
  const matchesChat = resource === undefined || loadedChat === undefined || resource.chatId === loadedChat.id;
  const receipts = useReceiptsV2(messageId, enabled && resource !== undefined && matchesChat);
  return <Inspector titleId="message-v2-details" eyebrow="Persisted message" title="Message details" subtitle={<span className="ui-v2-mono">{messageId}</span>} status={resource?.status ? <Status tone={resource.status === 'failed' ? 'failed' : resource.status === 'read' || resource.status === 'delivered' ? 'healthy' : 'pending'}>{humanizeToken(resource.status)}</Status> : undefined} modal onClose={onClose}>
    <div className="ui-v2-stack">
      {message.isPending ? <StateNotice value={{ axis: 'resource', state: 'initial-loading' }} /> : message.error && !resource ? <FailureNoticeV2 error={message.error} onRetry={() => message.refetch()} /> : resource && !matchesChat ? <StateNotice value={{ axis: 'resource', state: 'empty' }} detail="The selected message belongs to a different projected chat and is not shown in this context." /> : resource ? <><ProjectionStatusV2 meta={message.data?.meta} />{message.error ? <FailureNoticeV2 error={message.error} stale onRetry={() => message.refetch()} /> : null}<Surface title="Message facts" description="Projected status is authoritative; command acknowledgement is not delivery."><dl className="ui-v2-detail-list"><div><dt>Chat</dt><dd className="ui-v2-mono">{resource.chatId}</dd></div><div><dt>Direction</dt><dd>{humanizeToken(resource.direction)}</dd></div><div><dt>Type</dt><dd>{humanizeToken(resource.type)}</dd></div><div><dt>Provenance</dt><dd>{humanizeToken(resource.provenance)}</dd></div><div><dt>Created</dt><dd title={resource.createdAt}>{relativeTime(resource.createdAt) || resource.createdAt}</dd></div><div><dt>Delivered</dt><dd>{resource.deliveredAt ? relativeTime(resource.deliveredAt) : 'Not reported'}</dd></div><div><dt>Read</dt><dd>{resource.readAt ? relativeTime(resource.readAt) : 'Not reported'}</dd></div></dl></Surface></> : <StateNotice value={{ axis: 'resource', state: 'empty' }} />}
      {resource && matchesChat ? <Surface title="Delivery receipts" description="Per-recipient projected receipts.">{receipts.isPending ? <StateNotice value={{ axis: 'resource', state: 'initial-loading' }} /> : receipts.error && !receipts.data ? <FailureNoticeV2 error={receipts.error} onRetry={() => receipts.refetch()} /> : receipts.data ? <><ProjectionStatusV2 meta={receipts.data.meta} />{receipts.error ? <FailureNoticeV2 error={receipts.error} stale onRetry={() => receipts.refetch()} /> : null}{receipts.data.resource.length ? <ul className="ui-v2-receipt-list">{receipts.data.resource.map((receipt) => <li key={`${receipt.recipientJid}-${receipt.receiptType}-${receipt.receiptAt}`}><Status tone={receipt.receiptType === 'read' || receipt.receiptType === 'delivered' ? 'healthy' : 'pending'}>{humanizeToken(receipt.receiptType)}</Status><span className="ui-v2-mono">{receipt.recipientJid}</span><time title={receipt.receiptAt}>{relativeTime(receipt.receiptAt)}</time></li>)}</ul> : <StateNotice value={{ axis: 'resource', state: 'empty' }} detail="No per-recipient receipts have been projected." />}</> : null}</Surface> : null}
      <Button onClick={onClose}>Back to conversation</Button>
    </div>
  </Inspector>;
}
